add secp384r1 mapping
IdentityPython/pyMDOC-CBOR pull request #6
Opened 2024-03-26 14:02 UTC by PatStLouis

I'm leveraging this library to evaluate `deviceResponse` objects from third party vendors. This was a required addition, could I get a review on this?

2024-03-26 17:36 UTC, PascalDR commented on pymdoccbor/settings.py
> +    "secp384r1": 48,
```suggestion
    "secp384r1": 48,
    "secp521r1": 66
```

2024-03-26 17:40 UTC, PascalDR requested changes
Is better if we add secp521 too to support all cases of nist curves implemented in pycose.

For reference: [curves.py](https://github.com/TimothyClaeys/pycose/blob/master/pycose/keys/curves.py)

2024-04-10 17:26 UTC, PatStLouis reviewed
LGTM!

2024-04-10 17:29 UTC, PatStLouis commented
@PascalDR I committed the change request, are we good to request a merge?

2024-04-10 21:48 UTC, peppelinux approved these changes

2024-04-10 21:48 UTC, peppelinux commented on pymdoccbor/settings.py
> +    "secp521r1":  "P_521"
```suggestion
    "secp521r1": "P_521"
```

2024-04-10 21:50 UTC, peppelinux commented
@PatStLouis could I ask you to set 0.7.0 here?
https://github.com/IdentityPython/pyMDOC-CBOR/blob/main/pymdoccbor/__init__.py
this would allow us to create a new release

2024-04-10 22:53 UTC, PatStLouis commented
@peppelinux done!

2024-04-11 08:24 UTC, merged